/* eslint-disable react-refresh/only-export-components -- barrel: re-exports schemas alongside UI components */
import {
  fieldTypeSchema,
  selectOptionSchema,
  fieldDescriptorSchema,
  fieldDescriptorIntegerSchema,
  fieldDescriptorFloatSchema,
  fieldDescriptorStringSchema,
  fieldDescriptorSelectSchema,
  fieldDescriptorAddressSchema,
  fieldDescriptorUrlSchema,
  fieldDescriptorSideSchema,
  fieldDescriptorColorSchema,
  fieldDescriptorBooleanSchema,
  fieldDescriptorObjectListSchema,
  multipleObjectDescriptorSchema,
  fieldDescriptorMultipleObjectListSchema,
} from "./schema/schema";
import type {
  FieldTypes,
  FieldDataTypes,
  IFieldData,
  SelectOption,
  FieldDescriptor,
  FieldDescriptorAddress,
  FieldDescriptorBoolean,
  FieldDescriptorColor,
  FieldDescriptorFloat,
  FieldDescriptorInteger,
  FieldDescriptorString,
  MultipleObjectDescriptor,
  FieldDescriptorMultipleObjectList,
  FieldDescriptorObjectList,
  FieldDescriptorSelect,
  FieldDescriptorSide,
  FieldDescriptorUrl,
} from "./schema/schema";
import {FieldsGroup} from "./ui/fields-group";
import {FormFieldRender} from "./ui/form-field-render";

export type {
  FieldTypes,
  FieldDataTypes,
  IFieldData,
  SelectOption,
  FieldDescriptor,
  FieldDescriptorAddress,
  FieldDescriptorBoolean,
  FieldDescriptorColor,
  FieldDescriptorFloat,
  FieldDescriptorInteger,
  FieldDescriptorString,
  MultipleObjectDescriptor,
  FieldDescriptorMultipleObjectList,
  FieldDescriptorObjectList,
  FieldDescriptorSelect,
  FieldDescriptorSide,
  FieldDescriptorUrl,
};

export {
  fieldTypeSchema,
  selectOptionSchema,
  fieldDescriptorSchema,
  fieldDescriptorIntegerSchema,
  fieldDescriptorFloatSchema,
  fieldDescriptorStringSchema,
  fieldDescriptorSelectSchema,
  fieldDescriptorAddressSchema,
  fieldDescriptorUrlSchema,
  fieldDescriptorSideSchema,
  fieldDescriptorColorSchema,
  fieldDescriptorBooleanSchema,
  fieldDescriptorObjectListSchema,
  multipleObjectDescriptorSchema,
  fieldDescriptorMultipleObjectListSchema,
  FieldsGroup,
  FormFieldRender,
};